apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - quota-namespace-config.yaml
  - rbac-namespace-config.yaml
  - keycloak-vault-config.yaml
  - tenant-secret-mounts-config.yaml
  - tenant-argocd-vault-role-config.yaml
  - kube-vault-config.yaml