apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: tenant-secret-mounts
spec:
  labelSelector:
    matchExpressions:
      - key: team
        operator: Exists
      - key: app
        operator: Exists        
  templates:     
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: SecretEngineMount
        metadata:
          name: static-secrets-{{ .Labels.app }}
          namespace: vault-admin
        spec:
          authentication: 
            path: ${CLUSTER_NAME}
            role: vault-admin
            serviceAccount:
              name: default            
          type: kv
          path: /applications/{{ .Labels.cmdbID }}/{{ .Name }} 
      excludedPaths:
        - .metadata
        - .status
        - .spec.replicas
        - .spec.config
        - .spec.externalEntropyAccess
        - .spec.local
        - .spec.sealWrap                                     