apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: tenant-gitops-service-accounts
spec:
  labelSelector:
    matchExpressions:
      - key: team
        operator: Exists
      - key: application
        operator: Exists        
  templates:     
    - objectTemplate: |
        kind: ServiceAccount
        apiVersion: v1
        metadata:
          name: "{{ .Labels.team }}-tenant-gitops"
          namespace: vault-admin
      excludedPaths:	
        - .spec.replicas	
        - .metadata	
        - .status
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: "tenant-gitops"
          namespace: "{{ .Name }}"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: edit
        subjects:
        - kind: ServiceAccount
          name: "{{ .Labels.team }}-tenant-gitops"
          namespace: vault-admin
      excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: "{{ .Labels.team }}-tenant-gitops"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: argocd-reader
        subjects:
        - kind: ServiceAccount
          name: "{{ .Labels.team }}-tenant-gitops"
          namespace: vault-admin
      excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas                
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["list","get","watch"]
       