apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: tenant-gitops-secret-engine-roles
spec:
  labelSelector:
    matchExpressions:
      - key: team
        operator: Exists
      - key: application
        operator: Exists        
  templates:     
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: KubernetesSecretEngineRole
        metadata:
          name: "{{ .Labels.team }}"
          namespace: vault-admin
        spec:
          authentication: 
            path: ${CLUSTER_NAME}
            role: vault-admin
          path: /infra/clusters/${CLUSTER_NAME}/jwt
          serviceAccountName: "{{ .Labels.team }}-tenant-gitops"
          allowedKubernetesNamespaces: 
          - vault-admin
      excludedPaths:	
        - .spec.replicas	
        - .metadata	
        - .status