apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: ocp
  namespace: sso
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    id: ocp-client
    clientId: ocp-client
    secret: ocp-secret
    rootUrl: https://oauth-openshift.apps.rosa-vnm9f.m4a1.p1.openshiftapps.com/oauth2callback
    redirectUris:
      - /oidckeycloak