apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak.yaml
  - clients.yaml
  - keycloak-realm.yaml
  - oauth-secret.yaml
  - link.yaml
  - users.yaml
  - groups.yaml