apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: oauth-secret-policy
  namespace: sso
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace-example
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave  
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: oidc-secret
                  namespace: openshift-config
                type: Opaque
                data:
                  clientSecret: '{{hub (fromSecret "sso" (printf "keycloak-client-secret-ocp-%s" .ManagedClusterName ) "CLIENT_SECRET") | b64enc hub}}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: oauth-secret-policy
  namespace: sso
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: oauth-secret-policy
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: oauth-secret-policy
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: oauth-secret-policy
  namespace: sso
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values: ["prod","non-prod"]
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: sso
spec:
  clusterSet: default            
           