apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-app-only
rules:
- apiGroups: ["argoproj.io"] # "" indicates the core API group
  resources: ["applications"]
  verbs: ["*"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "team-a-tenant-argocd-app-only"
  namespace: "team-a"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-app-only
subjects:
- kind: ServiceAccount
  name: tenant-gitops
  namespace: tenant-gitops