apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: tenant-gitops-secrets
spec:
  labelSelector:
    matchLabels:
      tenant-gitops: "true"      
  templates:     
  - objectTemplate: |
      apiVersion: redhatcop.redhat.io/v1alpha1
      kind: VaultSecret
      metadata:
        name: "{{.Name}}-prod"
        namespace: tenant-gitops
      spec:
        vaultSecretDefinitions:
          - authentication:
              path: hub
              role: infra-secret-reader
              serviceAccount:
                name: default
            name: team_a
            path: /infra/clusters/prod/jwt/creds/{{.Name}}
            requestType: "POST"
            requestPayload:
              kubernetes_namespace: vault-admin
        output:
          name: "{{.Name}}-prod"
          stringData:
            name: "{{.Name}}-prod"
            server: https://api.prod.${PLATFORM_BASE_DOMAIN}:6443/?id={{.Name}}-prod
            clusterResources: "false"
            config: |
              {
                "bearerToken": "{{ "{{" }} .team_a.service_account_token {{ "}}" }}"
              }    
          type: Opaque
          labels:
            argocd.argoproj.io/secret-type: cluster
    excludedPaths:	
      - .spec.replicas	
      - .metadata	
      - .status
  - objectTemplate: |
      apiVersion: redhatcop.redhat.io/v1alpha1
      kind: VaultSecret
      metadata:
        name: "{{.Name}}-non-prod"
        namespace: tenant-gitops
      spec:
        vaultSecretDefinitions:
          - authentication:
              path: hub
              role: infra-secret-reader
              serviceAccount:
                name: default
            name: team_a
            path: /infra/clusters/non-prod/jwt/creds/{{.Name}}
            requestType: "POST"
            requestPayload:
              kubernetes_namespace: vault-admin
        output:
          name: "{{.Name}}-non-prod"
          stringData:
            name: "{{.Name}}-non-prod"
            server: https://api.prod.${PLATFORM_BASE_DOMAIN}:6443/?id={{.Name}}-non-prod
            clusterResources: "false"
            config: |
              {
                "bearerToken": "{{ "{{" }} .team_a.service_account_token {{ "}}" }}"
              }    
          type: Opaque
          labels:
            argocd.argoproj.io/secret-type: cluster
    excludedPaths:	
      - .spec.replicas	
      - .metadata	
      - .status
  - objectTemplate: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{.Name}}-hub"
        namespace: tenant-gitops
        labels:
          argocd.argoproj.io/secret-type: cluster
      type: Opaque
      stringData:
        name: "{{.Name}}-hub"
        server: https://api.${CLUSTER_BASE_DOMAIN}:6443/?id={{.Name}}-hub
        clusterResources: "false"
        config: ""
    excludedPaths:	
      - .spec.replicas	
      - .metadata	
      - .status
      - .data    