apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: team-a-prod
  namespace: tenant-gitops
spec:
  vaultSecretDefinitions:
    - authentication:
        path: hub
        role: infra-secret-reader
        serviceAccount:
          name: default
      name: team-a
      path: /infra/clusters/prod/jwt
      requestType: "POST"
  output:
    name: team-a-prod
    stringData:
      name: team-a-prod
      server: https://api.prod.${PLATFORM_BASE_DOMAIN}:6443
      clusterResources: "false"
      config: |
        {
          "bearerToken": "{{ .team-a.token }}"
        }    
    type: Opaque
    labels:
      argocd.argoproj.io/secret-type: cluster
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: team-a-non-prod
  namespace: tenant-gitops
spec:
  vaultSecretDefinitions:
    - authentication:
        path: hub
        role: infra-secret-reader
        serviceAccount:
          name: default
      name: team-a
      path: /infra/clusters/non-prod/jwt
      requestType: "POST"
  output:
    name: team-a-non-prod
    stringData:
      name: team-a-non-prod
      server: https://api.non-prod.${PLATFORM_BASE_DOMAIN}:6443
      clusterResources: "false"
      config: |
        {
          "bearerToken": "{{ .team-a.token }}"
        }    
    type: Opaque
    labels:
      argocd.argoproj.io/secret-type: cluster
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: team-b-prod
  namespace: tenant-gitops
spec:
  vaultSecretDefinitions:
    - authentication:
        path: hub
        role: infra-secret-reader
        serviceAccount:
          name: default
      name: team-b
      path: /infra/clusters/prod/jwt
      requestType: "POST"
  output:
    name: team-b-prod
    stringData:
      name: team-b-prod
      server: https://api.prod.${PLATFORM_BASE_DOMAIN}:6443
      clusterResources: "false"
      config: |
        {
          "bearerToken": "{{ .team-b.token }}"
        }    
    type: Opaque
    labels:
      argocd.argoproj.io/secret-type: cluster
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: team-b-non-prod
  namespace: tenant-gitops
spec:
  vaultSecretDefinitions:
    - authentication:
        path: hub
        role: infra-secret-reader
        serviceAccount:
          name: default
      name: team-b
      path: /infra/clusters/non-prod/jwt
      requestType: "POST"
  output:
    name: team-b-non-prod
    stringData:
      name: team-b-non-prod
      server: https://api.non-prod.${PLATFORM_BASE_DOMAIN}:6443
      clusterResources: "false"
      config: |
        {
          "bearerToken": "{{ .team-b.token }}"
        }    
    type: Opaque
    labels:
      argocd.argoproj.io/secret-type: cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: team-a-hub
  namespace: tenant-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: team-a-hub
  server: https://api.${CLUSTER_BASE_DOMAIN}:6443
  clusterResources: "false"
  config: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: team-b-hub
  namespace: tenant-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: team-b-hub
  server: https://api.${CLUSTER_BASE_DOMAIN}:6443
  clusterResources: "false"
  config: ""              
