apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: prod
  namespace: tenant-gitops
spec:
  vaultSecretDefinitions:
    - authentication:
        path: hub
        role: infra-secret-reader
        serviceAccount:
          name: default
      name: prod
      path: /infra/clusters/prod/jwt/creds/tenant-gitops
      requestType: "POST"
      requestPayload:
        kubernetes_namespace: vault-admin
  output:
    name: prod
    stringData:
      name: prod
      server: https://api.prod.${PLATFORM_BASE_DOMAIN}:6443
      clusterResources: "false"
      config: |
        {
          "bearerToken": "{{ .prod.service_account_token }}"
        }    
    type: Opaque
    labels:
      argocd.argoproj.io/secret-type: cluster
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: non-prod
  namespace: tenant-gitops
spec:
  vaultSecretDefinitions:
    - authentication:
        path: hub
        role: infra-secret-reader
        serviceAccount:
          name: default
      name: team_a
      path: /infra/clusters/non-prod/jwt/creds/tenant-gitops
      requestType: "POST"
      requestPayload:
        kubernetes_namespace: vault-admin      
  output:
    name: non-prod
    stringData:
      name: non-prod
      server: https://api.non-prod.${PLATFORM_BASE_DOMAIN}:6443
      clusterResources: "false"
      config: |
        {
          "bearerToken": "{{ .non-prod.service_account_token }}"
        }    
    type: Opaque
    labels:
      argocd.argoproj.io/secret-type: cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: hub
  namespace: tenant-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: hub
  server: https://api.${CLUSTER_BASE_DOMAIN}:6443
  clusterResources: "false"
  config: ""
             
