apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    argocd.argoproj.io/managed-by: tenant-gitops
    tenant-gitops: "true"
---    
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    argocd.argoproj.io/managed-by: tenant-gitops
    tenant-gitops: "true"    