default:
  app:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: false
    project: cluster-config
    labels:
      app-source: group-all
      repo: cluster-config
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/raffaelespazzoli/gitops-std-repo.git
      targetRevision: HEAD

projects:

  cluster-config:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    - https://github.com/raffaelespazzoli/gitops-std-repo
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'