applications:
  namespace-configuration-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: namespace-configuration-operator
    source:
      path: groups/multi-tenant/overlays/namespace-configuration-operator

  namespace-configurations:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: namespace-configuration-operator
    source:
      path: groups/multi-tenant/overlays/namespace-configurations

  group-sync-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: group-sync-operator
    source:
      path: groups/multi-tenant/overlays/group-sync-operator     

  group-sync-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: group-sync-configuration
    source:
      path: groups/multi-tenant/overlays/group-sync-configuration   


  vault-config-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: vault-config-operator
    source:
      path: groups/multi-tenant/overlays/vault-config-operator      