applications:
  namespace-configuration-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: namespace-configuration-operator
    source:
      path: groups/multi-tenant/overlays/namespace-configuration-operator

  namespace-configurations:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: namespace-configuration-operator
    source:
      path: groups/multi-tenant/overlays/namespace-configurations

  group-sync-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: group-sync-operator
    source:
      path: groups/multi-tenant/overlays/group-sync-operator     

  group-sync-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: group-sync-configuration
    source:
      path: groups/multi-tenant/overlays/group-sync-configuration

  oauth-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-config  
    source:
      path: components/oauth-config

  vault-admin:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: vault-admin  
    source:
      path: groups/multi-tenant/overlays/vault-admin      

  approved-namespaces-app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: default
    source:
      path: components/approved-namespaces-app

  kube-ops-view:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: kube-ops-view
    source:
      path: components/kube-ops-view                      


     