apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../components/vault-config-operator/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: alpha
    target:
      kind: Subscription
  - patch: |-
      - op: replace
        path: /spec/config/env/0/value
        value: https://vault.apps.rosa-vnm9f.m4a1.p1.openshiftapps.com
    target:
      kind: Subscription 