applications:

  kube-ops-view:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: kube-ops-view
    source:
      path: clusters/prod/overlays/kube-ops-view        

  oauth-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: oauth-config
    source:
      path: clusters/prod/overlays/oauth-config    

  approved-namespaces-app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: default
    source:
      path: clusters/prod/overlays/approved-namespaces-app                 