apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:  redhat-developer-hub

helmGlobals:
  chartHome: ../../../../.helm/charts

helmCharts:
  - name: developer-hub
    releaseName: redhat-developer-hub
    namespace: redhat-developer-hub
    valuesFile: values.yaml
