kind: ServiceAccount
apiVersion: v1
metadata:
  name: "tenant-gitops"
  namespace: vault-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["list","get","watch"]
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "tenant-gitops"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-reader
subjects:
- kind: ServiceAccount
  name: tenant-gitops
  namespace: vault-admin