---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: "Basic"
  overrides:
    components:
      - enabled: false
        name: insights
      - enabled: false
        name: cluster-backup
