---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: Basic
  enableClusterBackup: false
  ingress: {}
  overrides:
    components:
      - enabled: true
        name: app-lifecycle
      - enabled: true
        name: cluster-lifecycle
      - enabled: true
        name: cluster-permission
      - enabled: true
        name: console
      - enabled: true
        name: grc
      - enabled: false
        name: insights
      - enabled: true
        name: multicluster-engine
      - enabled: false
        name: multicluster-observability
      - enabled: true
        name: search
      - enabled: false
        name: submariner-addon
      - enabled: false
        name: volsync
      - enabled: false
        name: cluster-backup
  separateCertificateManagement: false
