apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - ../../../../components/vault

patches:
  - target:
      kind: Service
      name: vault-internal
    patch: |
      - op: remove
        path: /metadata/annotations/service.beta.openshift.io~1serving-cert-secret-name
  - target:
      kind: Route
      name: vault
      namespace: vault
    patch: |
      - op: replace
        path: /spec/host
        value: "vault.apps.rosa-vnm9f.m4a1.p1.openshiftapps.com"    
  - target:
      kind: ConsoleLink
    patch: |
      - op: replace
        path: /spec/href
        value: "https://vault.apps.rosa-vnm9f.m4a1.p1.openshiftapps.com"
           

helmCharts:
  - name: vault
    releaseName: vault
    namespace: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.25.0
    valuesFile: values.yaml
       