apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  #annotations:
  #  meta.upbound.io/example-id: iam/v1beta1/role
  #labels:
  #  testing.upbound.io/example-name: role
  name: crossplane-kube-system-control-plane-operator
spec:
  forProvider:
    managedPolicyArns:
       - arn:aws:iam::aws:policy/service-role/ROSAControlPlaneOperatorPolicy
    tags:
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true" 
      operator_namespace: kube-system
      operator_name: control-plane-operator
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRoleWithWebIdentity"
            ],
            "Effect": "Allow",
            "Condition": {
              "StringEquals": {
                "oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb:sub": [
                  "system:serviceaccount:kube-system:control-plane-operator"
                ]
              }
            },
            "Principal": {
              "Federated": "arn:aws:iam::803220779864:oidc-provider/oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb"
            }
          }
        ]
      }