applications:

  acm-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/overlays/acm-operator

  acm-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/overlays/acm-configuration

  rhsso-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: sso
    source:
      path: clusters/hub/overlays/rhsso-operator

  rhsso-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: sso
    source:
      path: clusters/hub/overlays/rhsso-configuration

  vault:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: vault
    source:
      path: clusters/hub/overlays/vault
    extraFields: |
      ignoreDifferences:
        - group: 'apps'
          jsonPointers:
            - /spec/volumeClaimTemplates
          kind: StatefulSet

  vault-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: vault-config
    source:
      path: clusters/hub/overlays/vault-config                      

  kube-ops-view:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: kube-ops-view
    source:
      path: clusters/hub/overlays/kube-ops-view

  patch-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: patch-operator
    source:
      path: clusters/hub/overlays/patch-operator   

  reflector-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: reflector-operator
    source:
      path: clusters/hub/overlays/reflector-operator     

  crossplane-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: crossplane-system
    source:
      path: clusters/hub/overlays/crossplane-operator      

  crossplane-providers:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: crossplane-system
    source:
      path: clusters/hub/overlays/crossplane-providers

  crossplane-provider-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: crossplane-system
    source:
      path: clusters/hub/overlays/crossplane-provider-config   

  redhat-developer-hub:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: redhat-developer-hub
    source:
      path: clusters/hub/overlays/redhat-developer-hub
    extraFields: |
      ignoreDifferences:
        - group: 'apps'
          jsonPointers:
            - /spec/volumeClaimTemplates
          kind: StatefulSet
        - group: 'route.openshift.io'
          jsonPointers:
            - /spec/host
          kind: Route                        

  prod:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: prod
    source:
      path: clusters/hub/overlays/prod     
    extraFields: |
      ignoreDifferences:
        - group: ''
          jsonPointers:
            - /data
          kind: Secret
        - group: 'hive.openshift.io'
          jsonPointers:
            - /spec/installed
          kind: ClusterDeployment          

  non-prod:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: non-prod
    source:
      path: clusters/hub/overlays/non-prod     
    extraFields: |
      ignoreDifferences:
        - group: ''
          jsonPointers:
            - /data
          kind: Secret
        - group: 'hive.openshift.io'
          jsonPointers:
            - /spec/installed
          kind: ClusterDeployment                         
                          