---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources: 
  - ./keycloak-provider-config.yaml
  - ./keycloak-credentials-secret.yaml
  - ./patches-rbac.yaml
  - ./patches.yaml
