apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: keycloak-provider-patches
spec:
  serviceAccountRef:
    name: default
  patches: 
    keycloak-credentials:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: crossplane-system
        name: keycloak-credentials
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: sso
        name: credential-rhsso
      - apiVersion: v1
        kind: ConfigMap
        namespace: sso
        name: openshift-service-ca.crt         
      patchTemplate: |
        {{ $value:= dict "username" ((index (index . 1).data "ADMIN_USERNAME") "password" ((index (index . 1).data "ADMIN_PASSWORD") "url" "https://keycloak.sso.svc.cluster.local:8443" "client_id" "admin-cli" "root_ca_certificate" (index (index . 2).data "service-ca.crt") "tls_insecure_skip_verify" "true" }}
        data:
          credentials: {{ $value | toJson | b64enc }}
      patchType: application/merge-patch+json   

