apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresqlinstances.aws.redhat-cop.redhat.com
spec:
  publishConnectionDetailsWithStoreConfigRef: 
    name: vault
  compositeTypeRef:
    apiVersion: redhat-cop.redhat.com/v1alpha1
    kind: XPostgreSQLInstance
  resources:
    - name: dbsubnetgroup
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: SubnetGroup
        metadata:
          name: subnetgroup
        spec:
          forProvider: 
            tags:
              Name: rds-instance
            subnetIds:
            - subnet-09edf108fe50de397
            - subnet-0808588ffa0e1a6b2  
      readinessChecks:	
        - matchCondition:	
            status: 'True'	
            type: Ready	
          type: MatchCondition              
      patches:              
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
          type: FromCompositeFieldPath                              
    - name: rdsinstance
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Instance
        metadata:
          name: instance        
        spec:
          forProvider:
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            instanceClass: db.t2.small
            username: adminuser
            engine: postgres
            engineVersion: "12"
            skipFinalSnapshot: true
            publiclyAccessible: false
            autoGeneratePassword: true
            passwordSecretRef:
              namespace: crossplane-system
              key: password
          publishConnectionDetailsTo:
            configRef:
              name: vault
      readinessChecks:	
        - matchCondition:	
            status: 'True'	
            type: Ready	
          type: MatchCondition            
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.publishConnectionDetailsTo.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
                type: Format
          type: FromCompositeFieldPath      
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.forProvider.passwordSecretRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-input"
                type: Format
          type: FromCompositeFieldPath      
        - fromFieldPath: "spec.parameters.size"
          toFieldPath: "spec.forProvider.instanceClass"
          transforms:
          - type: map
            map:
              small: db.t2.small
              medium: db.t2.medium
              large: db.t2.large
          type: FromCompositeFieldPath    
        - fromFieldPath: "spec.parameters.storage"
          toFieldPath: "spec.forProvider.allocatedStorage"
          type: FromCompositeFieldPath
        - fromFieldPath: "spec.parameters.availabilityZone"
          toFieldPath: "spec.forProvider.availabilityZone"
          type: FromCompositeFieldPath
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
          type: FromCompositeFieldPath                               
      connectionDetails:
        - fromFieldPath: "status.atProvider.endpoint"
          name: endpoint
        - fromFieldPath: "status.atProvider.address"
          name: host
        - fromFieldPath: "spec.forProvider.username"
          name: username
        - fromConnectionSecretKey: "attribute.password"
          name: password