---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#resources: 
#  - ./oidc.yaml

helmGlobals:
  chartHome: ./

helmCharts:
- name: cluster-role
  valuesFile: values.yaml

patches: [] 

#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization
#namespace: crossplane-system
#resources: 
#  - ./empty.yaml
 #- ./role.yaml
 #- ./oidc.yaml
 #- ./vpc.yaml
 #- ./private-subnet.yaml
#- ./aws-rds-postgresql-definition.yaml
#- ./aws-rds-postgresql-xrd.yaml   