apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/role
  labels:
    testing.upbound.io/example-name: role
  name: sample-role
spec:
  forProvider:
    managedPolicyArns:
       - arn:aws:iam::aws:policy/service-role/ROSAInstallerPolicy
    tags:
    - key: red-hat-managed
      value: true
    - key: rosa_hcp_policies
      value: true
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }