apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: ManagedOpenShift-HCP-ROSA-Installer-Role
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRole"
            ],
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam::710019948333:role/RH-Managed-OpenShift-Installer"
              ]
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSAInstallerPolicy
    tags:
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
      rosa_openshift_version: "4.15"
      rosa_role_prefix: ManagedOpenShift
      rosa_role_type: installer
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: ManagedOpenShift-HCP-ROSA-Support-Role
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRole"
            ],
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam::710019948333:role/RH-Technical-Support-11009103"
              ]
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSASRESupportPolicy
    tags:
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
      rosa_openshift_version: "4.15"
      rosa_role_prefix: ManagedOpenShift
      rosa_role_type: support
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: crossplane-kube-system-capi-controller-manager
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRoleWithWebIdentity"
            ],
            "Effect": "Allow",
            "Condition": {
              "StringEquals": {
                "oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb/sub": [
                  "system:serviceaccount:kube-system:capi-controller-manager"
                ]
              }
            },
            "Principal": {
              "Federated": "arn:aws:iam::803220779864/oidc-provider/oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb"
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSANodePoolManagementPolicy
    tags:
      operator_name: capi-controller-manager
      operator_namespace: kube-system
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: crossplane-kube-system-control-plane-operator
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRoleWithWebIdentity"
            ],
            "Effect": "Allow",
            "Condition": {
              "StringEquals": {
                "oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb/sub": [
                  "system:serviceaccount:kube-system:control-plane-operator"
                ]
              }
            },
            "Principal": {
              "Federated": "arn:aws:iam::803220779864/oidc-provider/oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb"
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSAControlPlaneOperatorPolicy
    tags:
      operator_name: control-plane-operator
      operator_namespace: kube-system
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: crossplane-kube-system-kms-provider
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRoleWithWebIdentity"
            ],
            "Effect": "Allow",
            "Condition": {
              "StringEquals": {
                "oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb/sub": [
                  "system:serviceaccount:kube-system:kms-provider"
                ]
              }
            },
            "Principal": {
              "Federated": "arn:aws:iam::803220779864/oidc-provider/oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb"
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSAKMSProviderPolicy
    tags:
      operator_name: kms-provider
      operator_namespace: kube-system
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: crossplane-kube-system-kube-controller-manager
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRoleWithWebIdentity"
            ],
            "Effect": "Allow",
            "Condition": {
              "StringEquals": {
                "oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb/sub": [
                  "system:serviceaccount:kube-system:kube-controller-manager"
                ]
              }
            },
            "Principal": {
              "Federated": "arn:aws:iam::803220779864/oidc-provider/oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb"
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSAKubeControllerPolicy
    tags:
      operator_name: kube-controller-manager
      operator_namespace: kube-system
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: crossplane-openshift-cloud-network-config-controller-cloud-crede
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRoleWithWebIdentity"
            ],
            "Effect": "Allow",
            "Condition": {
              "StringEquals": {
                "oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb/sub": [
                  "system:serviceaccount:kube-system:cloud-credentials"
                ]
              }
            },
            "Principal": {
              "Federated": "arn:aws:iam::803220779864/oidc-provider/oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb"
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSACloudNetworkConfigOperatorPolicy
    tags:
      operator_name: cloud-credentials
      operator_namespace: openshift-cloud-network-config-controller
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: crossplane-openshift-cluster-csi-drivers-ebs-cloud-credentials
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRoleWithWebIdentity"
            ],
            "Effect": "Allow",
            "Condition": {
              "StringEquals": {
                "oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb/sub": [
                  "system:serviceaccount:kube-system:ebs-cloud-credentials"
                ]
              }
            },
            "Principal": {
              "Federated": "arn:aws:iam::803220779864/oidc-provider/oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb"
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSAAmazonEBSCSIDriverOperatorPolicy
    tags:
      operator_name: ebs-cloud-credentials
      operator_namespace: openshift-cluster-csi-drivers
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: crossplane-openshift-image-registry-installer-cloud-credentials
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRoleWithWebIdentity"
            ],
            "Effect": "Allow",
            "Condition": {
              "StringEquals": {
                "oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb/sub": [
                  "system:serviceaccount:kube-system:installer-cloud-credentials"
                ]
              }
            },
            "Principal": {
              "Federated": "arn:aws:iam::803220779864/oidc-provider/oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb"
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSAImageRegistryOperatorPolicy
    tags:
      operator_name: installer-cloud-credentials
      operator_namespace: openshift-image-registry
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: crossplane-openshift-ingress-operator-cloud-credentials
  namespace: rosa-hcp-1
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRoleWithWebIdentity"
            ],
            "Effect": "Allow",
            "Condition": {
              "StringEquals": {
                "oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb/sub": [
                  "system:serviceaccount:kube-system:cloud-credentials"
                ]
              }
            },
            "Principal": {
              "Federated": "arn:aws:iam::803220779864/oidc-provider/oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb"
            }
          }
        ]
      }
    managedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/ROSAIngressOperatorPolicy
    tags:
      operator_name: cloud-credentials
      operator_namespace: openshift-ingress-operator
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    crossplane/subnet: capi-private-subnet
  name: capi-private-subnet
  namespace: rosa-hcp-1
spec:
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 10.0.6.0/24
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        crossplane/vpc: capi
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    crossplane/vpc: capi
  name: capi-vpc
  namespace: rosa-hcp-1
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    region: us-east-1
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: OpenIDConnectProvider
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: example
  namespace: rosa-hcp-1
spec:
  forProvider:
    clientIdList:
    - openshift
    - sts.amazonaws.com
    tags:
      red-hat-managed: "true"
    thumbprintList:
    - 9e99a48a9960b14926bb7f3b02e22da2b0ab7280
    url: https://oidc.op1.openshiftapps.com/2ag434nind6c19tid004jo232ehle0qb
