apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  identityProviders:
  - name: oidckeycloak
    mappingMethod: claim
    type: OpenID
    openID:
      clientID: <client-ID>
      clientSecret: 
        name: oidc-secret
      extraScopes: []
      issuer: https://keycloak-sso.apps.rosa-vnm9f.m4a1.p1.openshiftapps.com/auth/realms/myorg
      claims:
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
        groups:
        - groups