apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: keycloak
spec:
  authentication: 
    path: hub
    role: vault-admin
  path: oidc
  OIDCClientID: "vault"
  OIDCCredentials:
    secret: 
      name: keycloak-client-secret-vault
    usernameKey: CLIENT_ID
    passwordKey: CLIENT_SECRET
  OIDCDiscoveryURL: https://keycloak-sso.apps.rosa-vnm9f.m4a1.p1.openshiftapps.com/auth/realms/myorg