apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: keycloak
spec:
  authentication: 
    path: hub
    role: vault-admin
  path: keycloak
  OIDCClientID: "0oaau92rizgjZ2l935d7"
  OIDCCredentials:
    secret: 
      name: oktacredentials
    usernameKey: okta_client_id
    passwordKey: okta_client_secret
  OIDCDiscoveryURL: "<okta-server>"