apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./cluster-deployment.yaml
  - ./install-config-secret.yaml
  - ./machine-pool.yaml
  - ./patches-rbac.yaml
  - ./aws-creds-secret.yaml
  - ./pull-secret.yaml
  - ./patches.yaml
  - ./private-key-secret.yaml

helmGlobals:
  chartHome: ../../../../.helm/charts

helmCharts:
  - name: cluster-registration
    releaseName: prod
    namespace: prod
    valuesInline: 
      clusterName: prod
      clusterDomain: prod.m4a1.p1.openshiftapps.com    
      clusterSet: default
      repoURL: https://github.com/environment-aas/platform-iac.git
      labels:
        cloud: AWS
        vendor: OpenShift
        region: us-east-2

  - name: vault-cluster-registration
    releaseName: prod
    namespace: vault-admin
    