apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
  - ./namespace.yaml
  - ./cluster-deployment.yaml
  - ./install-config-secret.yaml
  - ./klusterletaddonconfig.yaml
  - ./machine-pool.yaml
  - ./managed-cluster.yaml
  - ./patches-rbac.yaml
  - ./aws-creds-secret.yaml
  - ./pull-secret.yaml
  - ./patches.yaml
  - ./private-key-secret.yaml