apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: ManagedOpenShift-HCP-ROSA-Installer-Role
spec:
  forProvider:
    managedPolicyArns:
       - arn:aws:iam::aws:policy/service-role/ROSAInstallerPolicy
    tags:
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_role_type: installer 
      rosa_managed_policies: "true" 
      rosa_openshift_version: 4.15 
      rosa_role_prefix: ManagedOpenShift
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRole"
            ],
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam::710019948333:role/RH-Managed-OpenShift-Installer"
              ]
            }
          }
        ]
      }